[project]
name = "litserve-gemma3-270m"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lightning-sdk>=2025.8.28",
    "litserve>=0.2.15",
    "torch>=2.8.0",
    "transformers>=4.55.4",
]
